### ISSUE TITLE
TypeError: Type 'NoneType' cannot be serialized (in etree)

### ISSUE THREAD

**Issue by lastorel** [scrapli/scrapli_netconf#68] opened 2021-06-17 09:48 UTC
**Describe the bug**
There is periodical issue while using `nornir_scrapli`. Script connects to devices and get summary information by custom tasks.
SOME random devices are found in `.failed_hosts`. Every run I see different devices there. There are 3 custom tasks and everytime random task fails.
Other devices return expected result.
I have no problems while connecting to single device by the same code. Never.

**To Reproduce**
1. Your script 
[junos.txt](https://github.com/scrapli/scrapli_netconf/files/6669056/junos.txt) 
2. What you're connecting to (vendor, platform, version)
JunOS 20.2R2 or 17.3R3. (~40 devices)
3. Anything else relevant
Last func def in `junos.txt` is called like that:
```
res = nr.run(task=junos.get_junos_summary_information)
```
nornir is configured like that:
```
runner:
    plugin: threaded
    options:
        num_workers: 20
```

**Expected behavior**
res.failed_hosts is empty.

**Stack Trace**
```
Traceback (most recent call last):
  File "/home/ubuntu/nbox/venv/lib/python3.8/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/ubuntu/nbox/venv/lib/python3.8/site-packages/nornir_scrapli/tasks/netconf_rpc.py", line 26, in netconf_rpc
    scrapli_response = scrapli_conn.rpc(filter_=filter_)
  File "/home/ubuntu/nbox/venv/lib/python3.8/site-packages/scrapli_netconf/driver/sync_driver.py", line 305, in rpc
    response.record_response(raw_response)
  File "/home/ubuntu/nbox/venv/lib/python3.8/site-packages/scrapli_netconf/response.py", line 109, in record_response
    self._record_response_netconf_1_0()
  File "/home/ubuntu/nbox/venv/lib/python3.8/site-packages/scrapli_netconf/response.py", line 143, in _record_response_netconf_1_0
    self.result = etree.tostring(self.xml_result, pretty_print=True).decode()
  File "src/lxml/etree.pyx", line 3445, in lxml.etree.tostring
TypeError: Type 'NoneType' cannot be serialized.
```

**OS (please complete the following information):**
 - OS: Ubuntu 18.04
 - scrapli version: 2021.1.30
 - scrapli_netconf version: 2021.1.30
 - nornir_scrapli version: 2021.1.30
 - nornir version: 3.1.1

**Additional context**

**Comment by lastorel** [comment] 2021-06-17 12:56
Well when I decreased `num_workers` to 5, that begun to work without problems.

**Comment by carlmontanari** [comment] 2021-06-17 18:01
Hey @lastorel 

Interesting! I'm not really seeing anything obvious -- from what I can tell basically what would have to happen to have that exception is that `etree.fromstring` would have to return `None` in [here](https://github.com/scrapli/scrapli_netconf/blob/c23893173671351255ce634408c428f7a72550c4/scrapli_netconf/response.py#L132-L143). which... I dont *think* I've ever seen it do... but clearly we are somewhere/somehow setting `self.xml_result` to `None` somewhere/somehow.

Would you be able to either get logs from when it fails, or perhaps simpler, put a `print` statement in `scrapli_netconf/response.py` at line 131 and 138 -- the first one we would probably want to print out `self.raw_result` to see what we are working with, then the second (line 138) would need to print `self.xml_result` to see what it got set to.

This may be a tricky one to figure out!

Thanks for opening this, hopefully we can get to the bottom of it soon!

Carl

**Comment by lastorel** [comment] 2021-06-18 10:17
OK.
Thats it:
```
        raw_result = self.raw_result
        self.xml_result = etree.fromstring(
            self.raw_result.replace(b"]]>]]>", b"").replace(
                b'<?xml version="1.0" encoding="UTF-8"?>', b""
            ),
            parser=PARSER,
        )
        xml_result = self.xml_result

        if self.strip_namespaces:
            self.xml_result = remove_namespaces(self.xml_result)
            self.result = etree.tostring(self.xml_result, pretty_print=True).decode()
        else:
            try:
                self.result = etree.tostring(self.xml_result, pretty_print=True).decode()
            except TypeError as e:
                with open("scrapli_netconf.log", "a") as fs:
                    fs.write(
                        "\nraw_result:\n" + \
                        str(raw_result) + \
                        "\nxml_result:\n" + \
                        str(xml_result)
                    )
                raise TypeError(e)
```

I think there is some problems of timeout/buffer operation:
[scrapli_netconf.log](https://github.com/scrapli/scrapli_netconf/files/6676342/scrapli_netconf.log)

**Comment by carlmontanari** [comment] 2021-06-18 16:08
Yeah that looks like it'll do it... what I don't understand yet is *how* we even get there. From poking around it looks like `from string` should always raise an exception (that we wouldn't be catching anywhere that I am aware of) if it cannot parse the raw result.

So that is upsetting for two reasons:

1) what the heck is going on w/ that `fromstring`!
2) more importantly -- why are we "losing" the first part of the result... this is the real problem that we'll need to track down.

I'm assuming from the nornir config that you are using the `system` transport -- could you try this with `paramiko` or `ssh2` and see if that changes things? Could you also snag full logs (preferably with system transport and also one of the other two so I can compare). If you would rather email me logs so they aren't posted here feel free: carl.r.montanari at gmail.

At the moment I am focusing on looking [here](https://github.com/scrapli/scrapli_netconf/blob/develop/scrapli_netconf/channel/sync_channel.py#L314-L321) and [here](https://github.com/scrapli/scrapli_netconf/blob/develop/scrapli_netconf/channel/sync_channel.py#L288-L292) but I cant reproduce this with my test vsrx so its a bit tough to really see whats going on.

I don't think that there is a timeout issue since we get the *end* of the message properly... we're just missing parts at the beginning. Thats leading me to think I've got something messed up with stripping/splitting out the channel input from the response... though the fact that it is seemingly random does not help with that theory.

Thanks for the help with this, I'm sure we'll figure it out... eventually 😁 

Carl

**Comment by lastorel** [comment] 2021-06-21 12:31
I get transport types here:
https://carlmontanari.github.io/scrapli/user_guide/project_details/

My results with 20 nornir threads on 46 QFX/EX devices (3 custom tasks):
**system**: 2 attempts, 3-9 failed devices, Executing time: 0:00:12.804934 ( + sometimes there are empty success task results)
**ssh2-python**: 2 attempts, 0 failed devices, Executing time: 0:00:20.937015
**paramiko**: 2 attempts, 0 failed devices, Executing time: 0:00:47.183018

Sorry for my inexperience I don't know how i can dive deeper and get low level transport logs without your help

**Comment by carlmontanari** [comment] 2021-06-21 19:53
ssh2python goes brrrrr 🤣 

Thanks so much for testing that @lastorel ! Super helpful and sadly confirms my suspicion that there may be an issue with system transport. Apologies for not mentioning how to snag the logs -- the easiest way is to use the `enable_basic_logging` function -- you *might* need to run this function *after* creating your nornir (typically `nr`) object since I'm not sure off hand what nornir is doing with logging. You can do this like:

```
from scrapli.logging import enable_basic_logging

< whatever in your normal code >

enable_basic_logging(file=True, level="debug")
```

That will spit out reasonably pretty looking logs to a file `scrapli.log` (if you prefer you can pass a string to a file path instead of `True` to the `file` argument). Probably with the logs I should be able to figure out some further troubleshooting steps and/or recreate it in some way so I can work on it.

Thanks a bunch for sticking with me on this!

Carl

**Comment by lastorel** [comment] 2021-06-22 08:43
Done. I sent logs to carl.r.montanari

**Comment by carlmontanari** [comment] 2021-06-22 21:46
I *think* this may be a regression related to #10 ... feels suspiciously the same... it looks like #30 is where the hopefully "fix" got pulled back out. Since you are just having issues with juniper we can can test this out by just quickly patching the "bare" `rpc` method. 

If you can remove the `\n` character from [here](https://github.com/scrapli/scrapli_netconf/blob/master/scrapli_netconf/driver/base_driver.py#L860) that *might* do the trick...

You can quickly find where that file is like `python -c "from scrapli_netconf.driver import base_driver; print(base_driver.__file__)"` 

🤞 hopefully that is our issue... I *think* it may be but I'm not 100% sure since the logs seem to just end after sending the return character like we see here:

```
899   | 2021-06-22 04:07:41,342 | DEBUG    | 10.23.250.204:22          | write: '<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="103"><get-vlan-information><detail/></get-vlan-information></rpc>\n]]>]]>'
910   | 2021-06-22 04:07:41,390 | INFO     | 10.23.250.204:22          | Read: b'<?xml version=\'1.0\' encoding=\'utf-8\'?>\n<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="103"><get-vlan-information><detail/></get-vlan-information></rpc>\n]]>]]><rpc-reply xmlns:junos="http://xml.juniper.net/junos/17.3R3/junos" << SNIP >>'
911   | 2021-06-22 04:07:41,391 | DEBUG    | 10.23.250.204:22          | write: '\n'
```

Normally I would expect/hope to see something else after this since we *should* be reading until we see the prompt *but* I am thinking/hoping that the return we send, in this case on log line 911, is causing the junos box to close the connection since it is not expecting a return to be sent at that time. I tested removing that new line character on the xrv9k, iosxe (csr1000v), and vsrx that I normally use to test and it looks like it is working fine. I made the change [here](https://github.com/scrapli/scrapli_netconf/blob/develop/scrapli_netconf/driver/base_driver.py#L554) which is a little different since there has been some clean up in the current develop branch, but should have the same impact as the other place I mentioned (that should actually exist in the version you are using).

Thanks for getting those logs and all the effort helping hunt this down!

Carl

**Comment by lastorel** [comment] 2021-06-23 08:59
That works. After removing `\n` in `_pre_rpc` there is no fails (system transport):
DEBUG: Executing time: 0:00:13.307756

such wow

**Comment by lastorel** [comment] 2021-06-23 09:52
also ssh2 transport works without issue too

**Comment by carlmontanari** [comment] 2021-06-24 00:10
Yes!!! Thank you so much for bearing with me and troubleshooting this.... can't believe this happened again haha... I will get this fixed merged to develop probably tomorrow... need to add some tests to make sure this doesn't regress again. I'll leave this open till I get some further testing done, write a real test or two, and get stuff merged.

Thanks again for your help, couldn't have got it figured out without your efforts!

Carl

**Comment by lastorel** [comment] 2021-06-24 08:10
I will continue to recomend your nice soft!

Thanks so much

**Comment by carlmontanari** [comment] 2021-06-25 23:00
Going to close this out now -- this is in develop and there is a test to keep me from breaking this again in the future! Thanks again for all the help, this was a pain in the ass to find/fix both this time and the first time lol, couldn't have done it without your help @lastorel !!

Carl

**Closed by carlmontanari** 2021-06-25 23:00 UTC
Labels: bug
