### ISSUE TITLE
ScrapliTimeout: Timed out reading from transport

### ISSUE THREAD

**Issue by RunSi** [scrapli/scrapli_netconf#24] opened 2020-12-01 18:12 UTC
**Describe the bug**
Configuring multiple telemetry streams causes the following error "ScrapliTimeout: Timed out reading from transport"

**To Reproduce**
When pushing the payload, as below, with just a single telemetry stream, then the configuration gets applied.
```python
from scrapli_netconf.driver import NetconfScrape
import logging

myconf = ```
<config>
               <mdt-config-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mdt-cfg">
                 <mdt-subscription>
                  <subscription-id>200</subscription-id>
                  <base>
                   <stream>yang-push</stream>
                   <encoding>encode-kvgpb</encoding>
                   <period>2000</period>
                   <xpath>/memory-ios-xe-oper:memory-statistics/memory-statistic</xpath>
                  </base>
                  <mdt-receivers>
                   <address>127.0.0.1</address>
                   <port>57500</port>
                   <protocol>grpc-tcp</protocol>
                  </mdt-receivers>
                 </mdt-subscription>
                </mdt-config-data>
              </config>```
conn = NetconfScrape(**my_device)
conn.open()
result = conn.edit_config(config=myconf, target="running")
print(result.result)
```

However when attempting to push multiple streams, thus changing _myconf_ to that below, the error occurs.  Please **Note** that the configuration does get applied, but scrapli_netconf raises a Timed out reading from transport error.

```xml
            <config>
               <mdt-config-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mdt-cfg">
                 <mdt-subscription>
                  <subscription-id>200</subscription-id>
                  <base>
                   <stream>yang-push</stream>
                   <encoding>encode-kvgpb</encoding>
                   <period>2000</period>
                   <xpath>/memory-ios-xe-oper:memory-statistics/memory-statistic</xpath>
                  </base>
                  <mdt-receivers>
                   <address>127.0.0.1</address>
                   <port>57500</port>
                   <protocol>grpc-tcp</protocol>
                  </mdt-receivers>
                 </mdt-subscription>
                    <mdt-subscription>
                  <subscription-id>102</subscription-id>
                  <base>
                   <stream>yang-push</stream>
                   <encoding>encode-kvgpb</encoding>
                   <period>500</period>
                   <xpath>/process-cpu-ios-xe-oper:cpu-usage/cpu-utilization/five-seconds</xpath>
                  </base>
                  <mdt-receivers>
                   <address>127.0.0.1</address>
                   <port>57500</port>
                   <protocol>grpc-tcp</protocol>
                  </mdt-receivers>
                  </mdt-subscription>
                </mdt-config-data>
              </config>
```

Using the above script with Vagrant CSR1000v - Cisco IOS XE Software, Version 16.11.01b

**Expected behavior**
Configuration applied to target device and script not timing out

**Stack Trace**
The traceback is:-
```bash
Traceback (most recent call last):
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/Users/sihart/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 653, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/myscrapli.py", line 51, in <module>
    result = conn.edit_config(config=myconf, target="running")
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli_netconf/driver/driver.py", line 144, in edit_config
    raw_response = self.channel.send_input_netconf(response.channel_input)
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli_netconf/channel/channel.py", line 210, in send_input_netconf
    channel_input=final_channel_input, strip_prompt=False, eager=True
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 114, in decorate
    wrapped_func=wrapped_func, args=args, kwargs=kwargs
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/Users/sihart/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/Users/sihart/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/channel/channel.py", line 248, in send_input
    output = self._read_until_input(channel_input=bytes_channel_input)
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli_netconf/channel/channel.py", line 180, in _read_until_input
    output += self._read_chunk()
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/channel/channel.py", line 49, in _read_chunk
    new_output = self.transport.read()
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 313, in requires_open_session_wrapper
    return wrapped_func(*args, **kwargs)
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 114, in decorate
    wrapped_func=wrapped_func, args=args, kwargs=kwargs
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 288, in multiprocessing_timeout
    self._handle_timeout()
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 192, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: Timed out reading from transport
```

**OS (please complete the following information):**
 - OS: Mac OS 10.15.7
scrapli               2020.11.15
scrapli-asyncssh      2020.10.10
scrapli-community     2020.11.15
scrapli-netconf       2020.11.15

**Comment by carlmontanari** [comment] 2020-12-01 18:19
Hey @RunSi -- can you try to crank up the `timeout_ops` and probably `timeout_transport` values to see if that sorts things out?

```
conn = NetconfScrape(**my_device, timeout_ops=180, timeout_transport=180)
```

Given that one applies just fine I'd guess this is just due to timeouts. In "normal" scrapli the timeout is configurable per operation like [here](https://github.com/carlmontanari/scrapli/blob/master/scrapli/driver/network_driver.py#L195) but that isn't really exposed in scrapli netconf (yet!). So its currently nicest to modify that in the constructor as outlined above.

Carl

**Comment by RunSi** [comment] 2020-12-01 18:31
@carlmontanari , thanks for the suggestion.  I adjusted the timeouts. The configuration gets applied but different traceback this time.

```bash
Traceback (most recent call last):
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 286, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/Users/sihart/.pyenv/versions/3.7.6/lib/python3.7/multiprocessing/pool.py", line 653, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/myscrapli.py", line 52, in <module>
    result = conn.edit_config(config=myconf, target="running")
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli_netconf/driver/driver.py", line 144, in edit_config
    raw_response = self.channel.send_input_netconf(response.channel_input)
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli_netconf/channel/channel.py", line 210, in send_input_netconf
    channel_input=final_channel_input, strip_prompt=False, eager=True
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 114, in decorate
    wrapped_func=wrapped_func, args=args, kwargs=kwargs
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 288, in multiprocessing_timeout
    self._handle_timeout()
  File "/Users/sihart/NORNIR_Stuff/NORN_netconf/venv/lib/python3.7/site-packages/scrapli/decorators.py", line 192, in _handle_timeout
    raise ScrapliTimeout(self.message)
scrapli.exceptions.ScrapliTimeout: Timed out sending input to device.
```

**Comment by carlmontanari** [comment] 2020-12-01 18:34
How long does the operation take w/ the netconf console command thing you had mentioned? It looks like you may just need to crank the timeout up even more based on the output but I could be wrong :D 

If cranking the timeout up further doesn't work could you snag logs please: [example.](https://github.com/carlmontanari/scrapli/blob/master/examples/logging/basic_logging.py)

**Comment by RunSi** [comment] 2020-12-01 18:39
[scrapli2.log](https://github.com/scrapli/scrapli_netconf/files/5624666/scrapli2.log)

Log attached.  When using netconf-console takes about 5 seconds

**Comment by carlmontanari** [comment] 2020-12-01 18:40
Cool, thanks @RunSi  -- will have to take a peak at this in more detail later today/this weekend. Will keep ya posted!

**Comment by carlmontanari** [comment] 2020-12-02 03:49
Hey again @RunSi -- possible short term "fix":

`conn = NetconfScrape(**my_device, transport="ssh2")` (you'll have to install scrapli-ssh2 as well)

I'm able to reproduce this, but don't have a great explanation. The current working theory is that the CSR is responding so so so so so fast (or even before the full input is sent??? which would be crazy but XE is kinda the Wild West for netconf things it seems...) that the reply is cutting off the actual input being read. Basically this is what scrapli is reading when it should be *just* reading the channel input we send:

```
#1191
<?xml version=\'1.0\' encoding=\'utf-8\'?>
<rpc xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><edit-config><target><running/></target><config>
   <mdt-config-data xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-mdt-cfg">
     <mdt-subscription>
      <subscription-id>200</subscription-id>
      <base>
       <stream>yang-push</stream>
       <encoding>encode-kvgpb</encoding>
       <period>2000</period>
       <xpath>/memory-ios-xe-oper:memory-statistics/memory-statistic</xpath>
      </base>
      <mdt-receivers>
       <address>127.0.0.1</address>
       <port>57500</port>
       <protocol>grpc-tcp</protocol>
      </mdt-receivers>
     </mdt-subscription>
        <mdt-subscription>
      <subscription-id>102</subscription-id>
      <base>
       <stream>yang-push</stream>
       <encoding>encode-kvgpb</encoding>
       <period>500</period>
       <xpath>/process-cpu-ios-xe-oper:cpu-usage/cpu-utilization/five-seconds</xpath>
      </base>
      <mdt-receivers>

#132
<?xml version="1.0" encoding="UTF-8"?>
<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><ok/></rpc-reply>
##
```

The input is chopped off and we already see the reply come back. It would be fairly trivial to add some logic to bail out of the "checking input" phase if we see an rpc-reply but I'd need to add another regex in there to make sure to peel the reply out fo the output (so we dont get it mixed up w/ the input as well) -- more regex is ok but slows things down a bit so if I can *not* do that id be happier :)

Will have to poke around at this more when I have more time. Will be curious if ssh2 fixes stuff up for you in the short term -- it seems to be 100% reliable on my end so hopefully that'll sort you out for now!

Carl

**Comment by RunSi** [comment] 2020-12-02 07:08
Great thanks @carlmontanari 

Have tested and that works with scrapli_netconf.  How would I achieve the same outcome with nornir_scrapli ?

**Comment by RunSi** [comment] 2020-12-02 09:13
@carlmontanari many thanks.  Yes that works for me.  Both with scrapli_netconf and nornir_scrapli

**Comment by carlmontanari** [comment] 2020-12-02 15:55
Awesome, glad to hear it! I'll keep this open as I need to figure out wtf is going on w/ system transport in this scenario! :) Thanks for opening this and your help @RunSi !

Carl

**Comment by carlmontanari** [comment] 2020-12-22 15:18
@RunSi Thanks again for opening this. I was able to re-create this issue a while back when we were first discussing it and I believe it is now fixed in the develop branch. If you have a second it would be great if you could test the fix! You can install the develop branch like so:

```
pip install -e git+https://github.com/scrapli/scrapli_netconf.git@develop#egg=scrapli_netconf
```

The TL;DR on the "fix" is that we were sending "pretty" xml to the device -- as soon as I removed all the newlines and sent just a "flattened" xml blob I got no more timeouts. I'm not 100% sure why the devices are behaving this way but it seems to have fixed the issue... the RFCs all have "pretty" xml in the examples, and up until this issue I did not encounter any problems.... but this fix does seem to work for me at least, so hopefully it does for you as well!

Thanks a bunch!

Carl

**Closed** 2021-01-17 16:09 UTC
Labels: bug
