### ISSUE TITLE
Error in async

### ISSUE THREAD

**Issue by miaow2** [scrapli/scrapli_netconf#13] opened 2020-10-22 12:05 UTC
**Describe the bug**
Hi Carl!
I'm trying to implement your example `async_edit_config_iosxr.py` on juniper, but have error in opening connection. With `NetconfScrape` driver all working well.

**To Reproduce**
1. Script
```
import asyncio
import logging

from scrapli_netconf.driver import AsyncNetconfScrape, NetconfScrape

logging.basicConfig(filename="scrapli.log", level=logging.DEBUG)
logger = logging.getLogger("scrapli")

JUNOS_DEVICE = {
    "host": "10.63.253.100",
    "auth_username": "admin",
    "auth_password": "admin",
    "auth_strict_key": False,
    "transport": "asyncssh",
    "port": 830,
}


async def main():
    # create scrapli_netconf connection just like with scrapli, open the connection
    conn = AsyncNetconfScrape(**JUNOS_DEVICE)
    await conn.open()
    print(conn.server_capabilities)
    await conn.close()


if __name__ == "__main__":
    asyncio.get_event_loop().run_until_complete(main())
```
2. Model Juniper QFX5110-48S, junos 17.3R3.10

**Expected behavior**
I want to get netconf capabilities.

**Stack Trace**
Traceback from script
```
Traceback (most recent call last):
  File "/home/sys.local/artem.kotik/scripts/lib/scrp-netconf.py", line 28, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/sys.local/artem.kotik/scripts/lib/scrp-netconf.py", line 22, in main
    await conn.open()
  File "/home/sys.local/artem.kotik/scripts/.venv/lib/python3.8/site-packages/scrapli_netconf/driver/async_driver.py", line 56, in open
    login_bytes = await self.transport.open_netconf()
  File "/home/sys.local/artem.kotik/scripts/.venv/lib/python3.8/site-packages/scrapli_netconf/transport/asyncssh_.py", line 41, in open_netconf
    self.stdin, self.stdout, self.stderr = await self.session.open_session(
  File "/home/sys.local/artem.kotik/scripts/.venv/lib/python3.8/site-packages/asyncssh/connection.py", line 3274, in open_session
    chan, session = await self.create_session(SSHClientStreamSession,
  File "/home/sys.local/artem.kotik/scripts/.venv/lib/python3.8/site-packages/asyncssh/connection.py", line 3250, in create_session
    session = await chan.create(session_factory, command, subsystem,
  File "/home/sys.local/artem.kotik/scripts/.venv/lib/python3.8/site-packages/asyncssh/channel.py", line 1064, in create
    raise ChannelOpenError(OPEN_REQUEST_PTY_FAILED,
asyncssh.misc.ChannelOpenError: PTY request failed
```
scrapli.log
```
INFO:scrapli.driver-10.63.253.100:Non-core transport `asyncssh` selected
INFO:scrapli.driver-10.63.253.100:Opening connection to 10.63.253.100
INFO:asyncssh:Opening SSH connection to 10.63.253.100, port 830
INFO:asyncssh:[conn=0] Connection to 10.63.253.100, port 830 succeeded
INFO:asyncssh:[conn=0]   Local address: 192.168.227.151, port 32816
DEBUG:asyncssh:[conn=0] Requesting key exchange
DEBUG:asyncssh:[conn=0] Received key exchange request
DEBUG:asyncssh:[conn=0] Beginning key exchange
DEBUG:asyncssh:[conn=0] Completed key exchange
INFO:asyncssh:[conn=0] Beginning auth for user admin
DEBUG:asyncssh:[conn=0] Trying keyboard-interactive auth
INFO:asyncssh:[conn=0] Auth for user admin succeeded
DEBUG:scrapli.transport-10.63.253.100:Authenticated to host 10.63.253.100 with password
DEBUG:asyncssh:[conn=0, chan=0] Set write buffer limits: low-water=16384, high-water=65536
INFO:asyncssh:[conn=0, chan=0] Requesting new SSH session
DEBUG:asyncssh:[conn=0] Received unknown global request: hostkeys-00@openssh.com
DEBUG:asyncssh:[conn=0, chan=0]   Terminal type: xterm
INFO:asyncssh:[conn=0, chan=0] Closing channel
```

**Screenshots**
If applicable, add screenshots to help explain your problem, but do note that formatted text is much preferred over
 screenshots!

**OS (please complete the following information):**
 - OS: centos 7.5
 - Python 3.8.3
 - scrapli==2020.10.10
 - scrapli-asyncssh==2020.10.10
 - scrapli-community==2020.9.19
 - scrapli-netconf==2020.10.10
 - scrapli-paramiko==2020.6.6
 - scrapli-ssh2==2020.6.6

**Additional context**
Authenfication succeeded, I think problem started when `Received unknown global request: hostkeys-00@openssh.com` happens. Maybe you've come across with this?

**Comment by carlmontanari** [comment] 2020-10-22 17:51
Can you try using port 22? I can reproduce this on my vSRX by connecting to 830 (but netconf is just running on port 22). Hopefully thats all the issue is!

I'll take a peak and see if I can add a nicer error/exception here as well!

**Comment by carlmontanari** [comment] 2020-10-22 18:30
Just pushed to develop branch and it should now catch this exception and have a message stating you may have the wrong port. Let me know if 1) changing the port works to fix things and 2) if you do try develop branch if the exception is handled properly and the message makes sense!

Thanks for raising this issue @miaow2 !

**Comment by miaow2** [comment] 2020-10-22 19:02
Thanks for quick response!
Changing port for 22 working well, thanks for the solution!
I've tried develop branch and get the message `scrapli.exceptions.ConnectionNotOpened: Failed to open Channel -- do you have the right port? Most often the netconf port is 22 or 830!`

But I've noticed strange thing:
NetconfScrape driver works well on 22 and 830 ports on the same device, but AsyncNetconfScrape only on 22, on 830 raises error from the issue

**Comment by carlmontanari** [comment] 2020-10-22 19:36
Now *that* is interesting! I can also reproduce that, and it looks like it is because we always request a pty and for whatever reason junos on port 830 is not happy about that.... I'm testing setting this option to "auto" which sounds like a reasonable choice per the asyncssh docs but will need some more testing to confirm if this is ok/smart or not :)

**Comment by carlmontanari** [comment] 2020-10-22 19:48
@miaow2 ok just pushed a tweak that has passed all tests and such, so 🤞 it should be good to go - let me know if that works better for ya?

Thanks again for the help with this!

**Comment by miaow2** [comment] 2020-10-22 21:07
Both drivers work good on both ports, thanks for your work!

**Comment by carlmontanari** [comment] 2020-10-22 21:09
Awesome! Thank you! Will close this out -- feel free to holler if anything else comes up!

**Closed by carlmontanari** 2020-10-22 21:09 UTC
Labels: bug
