### ISSUE TITLE
Extra Closing </interface> tag in the output provided by get_config 

### ISSUE THREAD

**Issue by matthewtakacs** [scrapli/scrapli_netconf#131] opened 2023-02-17 18:21 UTC
**Describe the bug**
When using get_config on an ASR920, the interface element looks to be prematurely closed with `</interface>`:

```
      <GigabitEthernet>
        <name>0/0/14</name>
        <logging>
          <event>
            <link-status/>
          </event>
        </logging>
        <cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-cdp"/>
        <tlv>
          <app/>
          <server-location/>
          <location/>
        </tlv>
      </GigabitEthernet>
      <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
        <auto>true</auto>
      </negotiation>
    </interface>
    <GigabitEthernet>
      <name>0/0/15</name>
      <logging>
        <event>
          <link-status/>
        </event>
      </logging>
      <cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-cdp">
        <tlv>
          <app/>
          <server-location/>
          <location/>
        </tlv>
      </cdp>
      <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
        <auto>true</auto>
      </negotiation>
    </GigabitEthernet>
```

This doesn't appear in the scrapli.log debug output, but `\n#4112\n`  does (see below).

**To Reproduce**

The following code:

```
from scrapli_netconf.driver import NetconfDriver

from scrapli.logging import enable_basic_logging

enable_basic_logging(file=True, level="debug")

my_device = {
    "host": "10.0.0.1",
    "auth_username": "user",
    "auth_password": "pass",
    "auth_strict_key": False,
    "port": 830,
    "transport": "ssh2"
}

conn = NetconfDriver(**my_device)
conn.open()
response = conn.get_config(source="running")
print(response.result)

```

Test device:
OS: IOS-XE 17.3.6
Product: ASR-920-24TZ-M

**Expected behavior**
Expect output without the extra `</interface>` tag in the output

**Stack Trace**
Script runs without error

**OS (please complete the following information):**
 - OS: Linux debian 4.9.0-7-amd64 # 1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
 - scrapli version 2022.7.30.post1
 - scrapli_netconf version 2023.1.30

**Other Info**

scrapli.log shows `\n#4112\n` in the preceeding GigabitEthernet element.

`<GigabitEthernet><name>0/0/13</name><logging><event><link-status/></event></logging><cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-cdp"><tlv><app></app><server-location/><location/></tlv></cdp><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>0/0/14</name><logging><event><link-status/></event></logging><cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-cdp">\n#4112\n<tlv><app></app><server-location/><location/></tlv></cdp><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>0/0/15</name><logging><event><link-status/></event></logging><cdp xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-cdp"><tlv><app></app><server-location/><location/></tlv></cdp><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet>`

**Comment by carlmontanari** [comment] 2023-02-18 17:02
👋 thanks for opening this. could you share the entire channel log for this please? also if you want to try updating the regex [here](https://github.com/scrapli/scrapli_netconf/blob/main/scrapli_netconf/response.py#L19) to look more like the one in scrapligo [here](https://github.com/scrapli/scrapligo/commit/150d4da5341c3e7cf8a88feebe15e1b9e9a392cf) that may be all we need to do. cant recall if that was a similar issue in scrapligo or not. alternatively testing w/ scrapligo would be great too to see if it works over there w/out issue.

**Comment by carlmontanari** [comment] 2023-02-20 19:56
> I couldn't get the scrapligo regex to work in python, It looks like it may match the whole chunk

ah yeah sorry I think we do it a bit differently in scrapligo... I cant keep it all straight in my head!

> I think something like either of the following would work to match initial chars 0 through 7, based on testing with various regex below:

I don't think the leading whitespace/newline should matter -- since we use multiline flag we should match any line starting w/ `#[somedigits]`. Also the trailing newline bits in the patterns you shared shouldn't matter either I dont think (subject to being wrong of course :D) since we should already be matching that with `\s*`. 

I think I need to see the full chunk to make sure I understand whats going on. its been a bit so I could totally be spacing things but I just had a quick look and tested a few things and it looks like things "should" work as is hah (obviously not, but we'll figure out why!)

In any case, we can test w/ something like:

```
def test_xyz():
    channel_input = "<something/>"
    result = """#520
<?xml version="1.0"?>
<rpc-reply message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
 <data>
  <components xmlns="http://openconfig.net/yang/platform">
   <component>
    <name>0/0-Virtual-Motherboard</name>
    <state>
     <description>Cisco IOS-XRv 9000 Virtual LC Motherboard</description>
     <name>0/0-Virtual-Motherboard</name>
     <type xmlns:idx="http://openconfig.net/yang/platform-types">idx:MODULE</type>
     <id>65538</id>
    </state>
   </component>
  </components>
 </data>
</rpc-reply>
##"""
    xml_input = etree.fromstring(text=channel_input)
    response = NetconfResponse(
        host="localhost",
        channel_input=channel_input,
        xml_input=xml_input,
        netconf_version=NetconfVersion.VERSION_1_1,
        failed_when_contains=[b"<rpc-error>"],
        strip_namespaces=True,
    )
    response.record_response(result=result.encode())

    assert 0
```

and obviously pop into debugger to see whats up. if we can get a reproducible payload that causes the issue should be easy to get a fix in!

thanks for the work on this!

**Comment by matthewtakacs** [comment] 2023-02-21 18:39
I've now reproduced this on a CSR1000V on code version 17.03.04a

I created a test in test_response.py that I think highlights the issue (really long to show chunking issue).

Thanks for looking into this.

```
def test_validate_chunk_regex():
    channel_input = "<something/>"
    result = '\n#4102\n<?xml version="1.0" encoding="UTF-8"?>\n<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101"><data><native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native"><interface><GigabitEthernet><name>1</name><description>NETCONF TEST</description><ip><address><dhcp></dhcp></address></ip><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>10</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>11</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>12</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>13</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>14</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>15</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>16</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>17</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>18</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>19</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>2</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>20</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>21</name><description>NETCONF TEST</description><logging><event>\n#3147\n<link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>22</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>23</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>24</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>3</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>4</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>5</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>6</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>7</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>8</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet><GigabitEthernet><name>9</name><description>NETCONF TEST</description><logging><event><link-status/></event></logging><mop><enabled>false</enabled><sysid>false</sysid></mop><negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet"><auto>true</auto></negotiation></GigabitEthernet></interface></native></data></rpc-reply>\n##\n'
    expected_result  = '''<rpc-reply xmlns="urn:ietf:params:xml:ns:netconf:base:1.0" message-id="101">
  <data>
    <native xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-native">
      <interface>
        <GigabitEthernet>
          <name>1</name>
          <description>NETCONF TEST</description>
          <ip>
            <address>
              <dhcp/>
            </address>
          </ip>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>10</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>11</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>12</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>13</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>14</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>15</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>16</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>17</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>18</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>19</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>2</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>20</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>21</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>22</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>23</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>24</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>3</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>4</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>5</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>6</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>7</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>8</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
        <GigabitEthernet>
          <name>9</name>
          <description>NETCONF TEST</description>
          <logging>
            <event>
              <link-status/>
            </event>
          </logging>
          <mop>
            <enabled>false</enabled>
            <sysid>false</sysid>
          </mop>
          <negotiation xmlns="http://cisco.com/ns/yang/Cisco-IOS-XE-ethernet">
            <auto>true</auto>
          </negotiation>
        </GigabitEthernet>
      </interface>
    </native>
  </data>
</rpc-reply>
'''

    xml_input = etree.fromstring(text=channel_input)
    response = NetconfResponse(
        host="localhost",
        channel_input=channel_input,
        xml_input=xml_input,
        netconf_version=NetconfVersion.VERSION_1_1,
        failed_when_contains=[b"<rpc-error>"],
        strip_namespaces=False,
    )
    response.record_response(result=result.encode())
    
    assert response.result == expected_result

```

**Comment by carlmontanari** [comment] 2023-02-21 18:40
perfect! thank you! ill investigate this weekend and we'll get it sorted out!

**Comment by matthewtakacs** [comment] 2023-02-21 20:58
Thanks! I think the issue is with `chunk_end_pos` being too small in `_record_response_netconf_1_1` due to the regex not returning the \n chars in the match object.

The \s and \n patterns in the regex don't seem to work when beside the $ anchor, being beside ^ doesn't cause a problem (although irrelevant for this code as the beginning index isn't used). ^ and $ alone match the \n condition but don't include the newlines in the result.

```
>>> test_string = b"\n#4893\nSome test text\n"
>>>
>>> re.search(pattern=(re.compile(rb"^#\d+$", flags=re.M | re.I)),string=test_string)
<re.Match object; span=(1, 6), match=b'#4893'>   <----- Both \n missing
>>>
>>> re.search(pattern=(re.compile(rb"^#\d+\s*", flags=re.M | re.I)),string=test_string)
<re.Match object; span=(1, 7), match=b'#4893\n'>   <----- Trailing \n present
>>>
>>> re.search(pattern=(re.compile(rb"^#\d+\s*$", flags=re.M | re.I)),string=test_string)
<re.Match object; span=(1, 6), match=b'#4893'>   <----- Both \n missing
>>>
>>> re.search(pattern=(re.compile(rb"^#\d+\n*$", flags=re.M | re.I)),string=test_string)
<re.Match object; span=(1, 6), match=b'#4893'>   <----- Both \n missing
>>>
>>> re.search(pattern=(re.compile(rb"^#\d+\n*", flags=re.M | re.I)),string=test_string)
<re.Match object; span=(1, 7), match=b'#4893\n'>   <----- Trailing \n present
>>>
>>> re.search(pattern=(re.compile(rb"^\s*#\d+\s*", flags=re.M | re.I)),string=test_string)
<re.Match object; span=(0, 7), match=b'\n#4893\n'>   <----- Both \n present

```

The missing trailing \n means that that `span()[1]` gives the wrong char position for `chunk_end_pos` .

This causes the result section of this bit of code...

```
result_sections.append(
                (chunk_size, self.raw_result[chunk_end_pos : chunk_end_pos + chunk_size])  # noqa
            )
```
to be -1 character out of line. So it takes the \n from the chunk size message and misses the trailing > before at the end of the chunk.

The problem only presents its self sometimes, as when this is rendered into XML, it doesn't seem to affect the XML tree if the ending > of a closing tag is truncated. If the ending > of an opening tag is truncated, this seems to cause problems.

Just dropping $ from the current regex seems to fix the issue (and hopefully doesn't break any other OSs).
`CHUNK_MATCH_1_1 = re.compile(rb"^#(?P<size>\d+)\s*", flags=re.M | re.I)`

Hope this helps with investigating!

**Comment by carlmontanari** [comment] 2023-02-24 21:44
👋 hey again @matthewtakacs 

thanks again for all the work/details here, super super helpful and appreciated! here's a branch w/ a fix I think -> https://github.com/scrapli/scrapli_netconf/tree/improve-11-chunk-handling

rather than faff about w/ things the way they are here I just ported the scrapligo regex over which I think solves the problem basically :D the test func you provided passed nicely for me now but would be great if you can confirm as well!

**Comment by matthewtakacs** [comment] 2023-02-24 22:06
Fantastic, thanks for jumping on this so quickly! Will test this out on an ASR920 when I'm back in work on Monday.

**Comment by matthewtakacs** [comment] 2023-02-28 16:59
This looks to work perfectly with longer outputs now, I see all the XML elements. Thank you!

**Comment by carlmontanari** [comment] 2023-02-28 17:34
awesome thanks a bunch for confirming! will get this merged by this weekend at the latest!

**Comment by carlmontanari** [comment] 2023-03-01 23:05
thanks again, closing and finishing up in #132!

**Closed by carlmontanari** 2023-03-01 23:05 UTC
Labels: bug
